services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: urbansense-mosquitto-secure
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./passwords:/mosquitto/config/passwords:ro
      - ./acl:/mosquitto/config/acl:ro
